"""Add user_id column on contract jobs

Revision ID: 140aadae5789
Revises: fff831e3a9f9
Create Date: 2024-03-26 02:30:39.777629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140aadae5789'
down_revision: Union[str, None] = 'fff831e3a9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_contract_jobs',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['daily_contract.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['daily_job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_contract_jobs')
    # ### end Alembic commands ###
