"""Create job table

Revision ID: 2c9f1c3c89a8
Revises: b980d420c159
Create Date: 2024-03-12 15:30:40.130143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9f1c3c89a8'
down_revision: Union[str, None] = 'b980d420c159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_job',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('default', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('editable', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_job')
    # ### end Alembic commands ###
