"""Create contract table

Revision ID: e460d90b3de2
Revises: 2c9f1c3c89a8
Create Date: 2024-03-12 15:32:56.075288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e460d90b3de2'
down_revision: Union[str, None] = '2c9f1c3c89a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_contract',
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('count_tasks', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_contract')
    # ### end Alembic commands ###
