"""edit count_tasks column on editable column 

Revision ID: f818ac010dd0
Revises: 9d3be7d639b2
Create Date: 2024-04-27 14:59:43.486986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f818ac010dd0'
down_revision: Union[str, None] = '9d3be7d639b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_contract', sa.Column('editable_tasks', sa.Integer(), nullable=False))
    op.drop_column('daily_contract', 'count_tasks')
    op.drop_column('daily_job', 'editable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_job', sa.Column('editable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('daily_contract', sa.Column('count_tasks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('daily_contract', 'editable_tasks')
    # ### end Alembic commands ###
