"""Create RoomContract intermediate table

Revision ID: fff831e3a9f9
Revises: 8e2e2d9ee22d
Create Date: 2024-03-16 12:06:49.730291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff831e3a9f9'
down_revision: Union[str, None] = '8e2e2d9ee22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_contract_rooms',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['daily_contract.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['daily_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('daily_task', sa.Column('contract_id', sa.Integer(), nullable=False))
    op.create_foreign_key('task_contract_fk', 'daily_task', 'daily_contract', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_contract_fk', 'daily_task', type_='foreignkey')
    op.drop_column('daily_task', 'contract_id')
    op.drop_table('daily_contract_rooms')
    # ### end Alembic commands ###
